bf16: true
cutoff_len: 2048
dataset: AesDataset
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: true
finetuning_type: lora
flash_attn: auto
freeze_multi_modal_projector: true
freeze_vision_tower: true
gradient_accumulation_steps: 10
image_max_pixels: 589824
image_min_pixels: 1024
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: Qwen3-VL-8B
num_train_epochs: 1.0
optim: adamw_torch
output_dir: saves/Qwen3-VL-8B-Instruct/lora/train_model
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 30
stage: sft
template: qwen3_vl_nothink
trust_remote_code: true
video_max_pixels: 65536
video_min_pixels: 256
warmup_steps: 0
